- name: Install packages required for ruby install
  apt: pkg={{item}} state=latest update_cache=yes install_recommends=yes
  with_items:
    - build-essential
    - autoconf
    - automake
    - bison
    - openssl
    - curl
    - pkg-config
    - postgresql-server-dev-9.1
    - tklib
    - zlib1g
    - zlib1g-dev
    - libc6-dev
    - libncurses5-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - libreadline-dev
    - libmysqlclient-dev
    - libcurl4-openssl-dev
    - libxslt1-dev
    - libxml2-dev
    - libxml2
    - libtool

- name: Install Ruby
  command: rbenv install {{ruby_version}}
  sudo: no

- name: Set ruby version
  command: rbenv global {{ruby_version}}
  sudo: no

- name: Update rubygems
  command: gem update --system
  sudo: no

- name: Install gems
  gem: name={{item}} state=latest
  with_items:
    - rake
    - bundler
  sudo: no

